version: "3"
services:
    pronunciation-api:
        container_name: pronunciation_api
        image: bi1101/pronunciation-api:latest
        ports: ["8080:8080"]
        restart: unless-stopped

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30